# Generated by Django 3.2.9 on 2021-11-28 22:54

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixation_title', models.CharField(max_length=50)),
                ('category', models.TextField(choices=[('Other', 'Other'), ('Music', 'Music')], default='Other')),
                ('description', models.CharField(max_length=240, null=True)),
                ('img_url', models.CharField(max_length=1000, null=True)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_song', models.CharField(max_length=64, null=True)),
                ('fixation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fixation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_song', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('spotify_authenticated_ind', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixationSessionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_hints_ind', models.BooleanField(default=True)),
                ('multiple_choice_ind', models.BooleanField(default=True)),
                ('random_shuffle_ind', models.BooleanField(default=True)),
                ('stop_on_answer_ind', models.BooleanField(default=False)),
                ('time_limit', models.IntegerField(choices=[(30, 'Fast'), (60, 'Moderate'), (120, 'Slow'), (1000000, 'Unlimited')], default=1000000)),
                ('active_ind', models.BooleanField(default=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('fixation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fixationsession')),
            ],
        ),
        migrations.CreateModel(
            name='FixationSessionPlayer',
            fields=[
                ('player_session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=16)),
                ('active_ind', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('fixation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fixationsession')),
            ],
        ),
        migrations.AddField(
            model_name='fixationsession',
            name='hosted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='fixation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
