# Generated by Django 3.2.9 on 2022-03-13 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_fixationsession_hosted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixation',
            name='temp_field',
        ),
        migrations.AddField(
            model_name='fixation',
            name='default_duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='fixation',
            name='spotify_random_start_ind',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FixationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_idx', models.IntegerField()),
                ('question_txt', models.CharField(max_length=512)),
                ('multiple_choice_ind', models.BooleanField(default=True)),
                ('img_url', models.CharField(max_length=512, null=True)),
                ('video_playback_url', models.CharField(max_length=512, null=True)),
                ('question_category', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fixation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fixation')),
            ],
        ),
        migrations.CreateModel(
            name='FixationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_txt', models.CharField(max_length=512)),
                ('correct_answer_ind', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fixationquestion')),
            ],
        ),
    ]
