# Generated by Django 3.2.9 on 2022-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220312_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixationsessionsettings',
            name='random_spotify_start',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
