# Generated by Django 3.2.9 on 2022-04-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fixationsessionsettings_random_spotify_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixationsessionsettings',
            old_name='random_spotify_start',
            new_name='spotify_random_start_ind',
        ),
    ]
