# Generated by Django 3.2.9 on 2022-04-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_random_spotify_start_fixationsessionsettings_spotify_random_start_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixationanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.fixationquestion'),
        ),
    ]
