# Generated by Django 3.2.9 on 2021-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypertriviationuser',
            name='session_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
