# Generated by Django 3.2.9 on 2021-12-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_hypertriviationuser_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypertriviationuser',
            name='session_key',
        ),
    ]
