# Generated by Django 3.2.9 on 2022-03-05 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_fixation_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('playlist_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('href', models.CharField(max_length=256)),
                ('img_url', models.CharField(max_length=256)),
                ('owner_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song_id', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('refresh_token', models.CharField(max_length=150, null=True)),
                ('access_token', models.CharField(max_length=150, null=True)),
                ('expires_in', models.DateTimeField(null=True)),
                ('token_type', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
