# Generated by Django 3.2.9 on 2021-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='session_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
