# Generated by Django 3.2.9 on 2021-12-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20211130_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='session_key',
        ),
    ]
