# Generated by Django 3.2.9 on 2021-12-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_remove_spotifytoken_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='spotify_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
